# Site settings
title: Ralph's ML Blog
email: ralph.angelus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
	Welcome to Ralph's ML blog! 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://edezhath.github.io" # the base hostname & protocol for your site

github_username:  edezhath

# Build settings
markdown: kramdown
