# Site settings
name: Scientia Ex Machina
title: Scientia Ex Machina
email: ralph.angelus (AT) gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://edezhath.github.io/" # the base hostname & protocol for your site
description: ML for fun and edification


footer-links:
  github: edezhath
  linkedin: edezhath


github_username:  edezhath
linkedin_username: edezhath
linkedin: edezhath

# Build settings
markdown: kramdown

include: [_posts]
